const fs = require('fs');
const t = fs.readFileSync('packages/app-shell/src/renderer/busy-phrases.js', 'utf8');
const m = t.match(/__BUSY_PHRASES\s*=\s*(\[[\s\S]*?\]);/);
const a = eval(m[1]);
const s = new Set(a);
console.log('count', a.length);
console.log('unique', s.size);
const bad = a.filter(x => typeof x !== 'string' || !x || x.trim().length <= 3);
console.log('too_short_or_empty', bad.length);
const lens = a.map(x => x.trim().length);
console.log('min', Math.min.apply(null, lens), 'max', Math.max.apply(null, lens));
const minp = a.reduce((m, x) => (x.trim().length < m.trim().length ? x : m), a[0]);
const maxp = a.reduce((m, x) => (x.trim().length > m.trim().length ? x : m), a[0]);
console.log('minp', minp);
console.log('maxp', maxp);
console.log('sample1', a[10]);
console.log('sample2', a[500]);
console.log('sample3', a[980]);
const q = a.filter(x => x.indexOf('?') >= 0 || x.indexOf('\uff1f') >= 0);
console.log('question_marks', q.length);
console.log('rotate_ok', /__BUSY_ROTATE_MS\s*=\s*12000/.test(t));
