/**
 * Electron preload — 白名单 API
 */
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('warmy', {
  hardware: () => ipcRenderer.invoke('warmy:hardware'),
  listInstances: () => ipcRenderer.invoke('warmy:list-instances'),
  spawnInstance: (cfg) => ipcRenderer.invoke('warmy:spawn-instance', cfg),
  stopInstance: (id) => ipcRenderer.invoke('warmy:stop-instance', id),
  securityMode: () => ipcRenderer.invoke('warmy:security-mode'),
  setSecurityMode: (mode) => ipcRenderer.invoke('warmy:set-security-mode', mode),
  memoryRecall: (q) => ipcRenderer.invoke('warmy:memory-recall', q),
  memoryAppend: (body) => ipcRenderer.invoke('warmy:memory-append', body),
  memoryRetrieve: (payload) => ipcRenderer.invoke('warmy:memory-retrieve', payload),
  memoryStatus: () => ipcRenderer.invoke('warmy:memory-status'),
  memoryRebuild: () => ipcRenderer.invoke('warmy:memory-rebuild'),
  i18n: (locale) => ipcRenderer.invoke('warmy:i18n', locale),
  localeInfo: () => ipcRenderer.invoke('warmy:locale-info'),
  setThemeSource: (s) => ipcRenderer.invoke('warmy:set-theme-source', s),
  themeInfo: () => ipcRenderer.invoke('warmy:theme-info'),
  listModels: (cfg) => ipcRenderer.invoke('warmy:list-models', cfg),
  pickSound: () => ipcRenderer.invoke('warmy:pick-sound'),
  checkUpdate: () => ipcRenderer.invoke('warmy:check-update'),
  pickFile: () => ipcRenderer.invoke('warmy:pick-file'),
  groupCreate: (cfg) => ipcRenderer.invoke('warmy:group-create', cfg),
  groupList: () => ipcRenderer.invoke('warmy:group-list'),
  updateSourceGet: () => ipcRenderer.invoke('warmy:update-source-get'),
  updateSourceSet: (payload) => ipcRenderer.invoke('warmy:update-source-set', payload),
  groupMessage: (msg) => ipcRenderer.invoke('warmy:group-message', msg),
  groupJoinInstance: (groupId, instanceId) => ipcRenderer.invoke('warmy:group-join-instance', groupId, instanceId),
  boardTasks: (groupId) => ipcRenderer.invoke('warmy:board-tasks', groupId),
  boardEvents: () => ipcRenderer.invoke('warmy:board-events'),
  boardAggregate: () => ipcRenderer.invoke('warmy:board-aggregate'),
  setProvider: (cfg) => ipcRenderer.invoke('warmy:set-provider', cfg),
  getProvider: () => ipcRenderer.invoke('warmy:get-provider'),
  chatSend: (msg) => ipcRenderer.invoke('warmy:chat-send', msg),
  checkpointCreate: (phase) => ipcRenderer.invoke('warmy:checkpoint-create', phase),
  checkpointList: () => ipcRenderer.invoke('warmy:checkpoint-list'),
  checkpointRollback: (id) => ipcRenderer.invoke('warmy:checkpoint-rollback', id),
  knowledgeQuery: (q) => ipcRenderer.invoke('warmy:knowledge-query', q),
  knowledgeAddEvent: (ev) => ipcRenderer.invoke('warmy:knowledge-add-event', ev),
  setInsertMode: (sessionId, mode) => ipcRenderer.invoke('warmy:set-insert-mode', sessionId, mode),
  getInsertMode: (sessionId) => ipcRenderer.invoke('warmy:get-insert-mode', sessionId),
  metricsSummary: () => ipcRenderer.invoke('warmy:metrics-summary'),
  metricsTurns: () => ipcRenderer.invoke('warmy:metrics-turns'),
  metricsTools: () => ipcRenderer.invoke('warmy:metrics-tools'),
  chatLog: (payload) => ipcRenderer.invoke('warmy:chat-log', payload),
  chatLogRestore: () => ipcRenderer.invoke('warmy:chat-log-restore'),
  settingsGet: () => ipcRenderer.invoke('warmy:settings-get'),
  settingsSave: (partial) => ipcRenderer.invoke('warmy:settings-save', partial),
  // ADR 004：执行环境探测（只探测，不安装不下载不提权）与启停（只接受预定义 id + 'start'|'stop'）
  containerProbe: (opts) => ipcRenderer.invoke('warmy:container-probe', opts),
  containerAction: (payload) => ipcRenderer.invoke('warmy:container-action', payload),
  // 容器内 shell（P4，= 控制台本体）：只接受 { runtimeId, action, sessionId, data }；
  // action 是**枚举**（open/write/close/status），**不接受任何命令字符串**。
  containerShell: (payload) => ipcRenderer.invoke('warmy:container-shell', payload),
  // 项目可用性状态（容器开发项目+容器没起 ⇒ 不可用；被创建者停用 ⇒ 不可用；
  // 两者都等同"创建者下线"、**历史仍可读**）。渲染层的**唯一**事实来源，不自己推一套。
  projectState: (payload) => ipcRenderer.invoke('warmy:project-state', payload),
  // 右键菜单：启用/停用项目（只接受 { sessionId }；只有创建者能调用，容器没起时启用会被拒并给引导）
  projectEnable: (payload) => ipcRenderer.invoke('warmy:project-enable', payload),
  projectDisable: (payload) => ipcRenderer.invoke('warmy:project-disable', payload),
  // 右键菜单：切换容器（只接受 { sessionId, runtimeId }；runtimeId 必须是已探测到的预定义 id）
  projectSetContainer: (payload) => ipcRenderer.invoke('warmy:project-set-container', payload),
  // 右侧三块面板的真实数据：最近改动文件 / 其他文件 / 生成的产品
  projectFiles: (payload) => ipcRenderer.invoke('warmy:project-files', payload),
  // 项目环境状态（当前容器 / 固化能力 / 上次固化时间）与「固化当前环境」
  // 固化能力**按运行时区分**（Docker/Podman 可 commit；WSL 没有 commit）；不能固化就如实拒绝。
  projectEnvStatus: (payload) => ipcRenderer.invoke('warmy:project-env-status', payload),
  projectEnvSolidify: (payload) => ipcRenderer.invoke('warmy:project-env-solidify', payload),
  // ADR 004 第十六批：
  //  · projectEnvRollback  = 回滚到固化点（真的从固化镜像起一个容器）
  //  · projectExec         = 把项目的命令送进容器（只接受**固定命令枚举**，没有命令字符串）
  //  · projectLedger       = 工具文件访问台账（**项目级、成员可见**）
  //  · projectSetDirectory = 把项目目录记进项目记录（目录由主进程弹窗选）
  //  · projectFsGuard      = 宿主目录加锁/撤销/状态（最小侵入、可一键撤销）
  projectEnvRollback: (payload) => ipcRenderer.invoke('warmy:project-env-rollback', payload),
  projectExec: (payload) => ipcRenderer.invoke('warmy:project-exec', payload),
  projectLedger: (payload) => ipcRenderer.invoke('warmy:project-ledger', payload),
  projectSetDirectory: (payload) => ipcRenderer.invoke('warmy:project-set-directory', payload),
  projectFsGuard: (payload) => ipcRenderer.invoke('warmy:project-fs-guard', payload),
  // 「运行」产物：入口路径**由主进程自己解析**（渲染层只给 sessionId），且必须可在本机运行
  productRun: (payload) => ipcRenderer.invoke('warmy:product-run', payload),
  // 待执行队列持久化（渲染层 state.queues）+ Router 队列只读快照
  uiQueuesGet: () => ipcRenderer.invoke('warmy:ui-queues-get'),
  uiQueuesSet: (queues) => ipcRenderer.invoke('warmy:ui-queues-set', { queues }),
  routerQueuesGet: () => ipcRenderer.invoke('warmy:router-queues-get'),
  profileGet: () => ipcRenderer.invoke('warmy:profile-get'),
  appInfo: () => ipcRenderer.invoke('warmy:app-info'),
  skillsList: () => ipcRenderer.invoke('warmy:skills-list'),
  skillsRemove: (id) => ipcRenderer.invoke('warmy:skills-remove', id),
  skillsImport: () => ipcRenderer.invoke('warmy:skills-import'),
  pickDirectory: () => ipcRenderer.invoke('warmy:pick-directory'),
  privacyConsentSet: (consent) => ipcRenderer.invoke('warmy:privacy-consent-set', consent),
  appQuit: (reason) => ipcRenderer.invoke('warmy:app-quit', reason),
  identityCredential: () => ipcRenderer.invoke('warmy:identity-credential'),
  identityBackupImport: (payload) => ipcRenderer.invoke('warmy:identity-backup-import', payload),
  pluginsScanDirsGet: () => ipcRenderer.invoke('warmy:plugins-scan-dirs-get'),
  pluginsScanDirsSet: (dirs) => ipcRenderer.invoke('warmy:plugins-scan-dirs-set', dirs),
  pluginsScan: () => ipcRenderer.invoke('warmy:plugins-scan'),
  assistList: (sessionId) => ipcRenderer.invoke('warmy:assist-list', sessionId),
  assistUpsert: (payload) => ipcRenderer.invoke('warmy:assist-upsert', payload),
  skillsPaths: () => ipcRenderer.invoke('warmy:skills-paths'),
  // Skill auto-discovery directories ride the EXISTING settings channel.
  skillsScanDirsGet: () => ipcRenderer.invoke('warmy:skills-scan-dirs-get'),
  skillsScanDirsSet: (dirs) => ipcRenderer.invoke('warmy:skills-scan-dirs-set', dirs),
  skillsSetEnabled: (payload) => ipcRenderer.invoke('warmy:skills-set-enabled', payload),
  projectMemoryGet: (payload) => ipcRenderer.invoke('warmy:project-memory-get', payload),
  projectMemorySet: (payload) => ipcRenderer.invoke('warmy:project-memory-set', payload),
  aiQuestionOpen: (payload) => ipcRenderer.invoke('warmy:ai-question-open', payload),
  aiQuestionList: (groupId) => ipcRenderer.invoke('warmy:ai-question-list', groupId),
  aiQuestionAnswer: (payload) => ipcRenderer.invoke('warmy:ai-question-answer', payload),
  trayTooltip: (text) => ipcRenderer.invoke('warmy:tray-tooltip', text),
  profileSave: (p) => ipcRenderer.invoke('warmy:profile-save', p),
  // 身份层（ADR 003）：指纹 / 代次 / 名片 / 换证 / 备份导出
  identityInfo: () => ipcRenderer.invoke('warmy:identity-info'),
  identityRotate: (payload) => ipcRenderer.invoke('warmy:identity-rotate', payload),
  identityBackupExport: (payload) => ipcRenderer.invoke('warmy:identity-backup-export', payload),
  identityVerifyRotation: (payload) => ipcRenderer.invoke('warmy:identity-verify-rotation', payload),
  identitySetPassphrase: (payload) => ipcRenderer.invoke('warmy:identity-set-passphrase', payload),
  // 本机留存的名片历史（换证横幅展示"旧联系方式"用；不从换证声明读）
  identityCardHistory: () => ipcRenderer.invoke('warmy:identity-card-history'),
  // 接收方侧：对端名片 + 7 天冻结期（本机各自判定）
  identityPeerContact: (fingerprint) => ipcRenderer.invoke('warmy:identity-peer-contact', fingerprint),
  identityPeerCard: (payload) => ipcRenderer.invoke('warmy:identity-peer-card', payload),
  identityPeerRotation: (payload) => ipcRenderer.invoke('warmy:identity-peer-rotation', payload),
  identityPeerConfirm: (fingerprint) => ipcRenderer.invoke('warmy:identity-peer-confirm', fingerprint),
  // 身份变更横幅（附六）：本机换证 + 对端换证；ack 必须审计成功才算数
  identityChanges: (payload) => ipcRenderer.invoke('warmy:identity-changes', payload),
  identityChangeAcknowledge: (payload) => ipcRenderer.invoke('warmy:identity-change-ack', payload),
  // 本机已知的**全部**对端名片状态（「有谁换了证」）
  identityPeers: () => ipcRenderer.invoke('warmy:identity-peers'),
  // 成员证书 + 吊销列表（ADR §附八.8）：签发 / 换证重签 / 吊销 / 收证书 / 同步吊销列表 / 名册判定
  membershipList: (payload) => ipcRenderer.invoke('warmy:membership-list', payload),
  membershipAuthorize: (payload) => ipcRenderer.invoke('warmy:membership-authorize', payload),
  membershipIssue: (payload) => ipcRenderer.invoke('warmy:membership-issue', payload),
  membershipRotate: (payload) => ipcRenderer.invoke('warmy:membership-rotate', payload),
  membershipRevoke: (payload) => ipcRenderer.invoke('warmy:membership-revoke', payload),
  membershipReceiveCert: (payload) => ipcRenderer.invoke('warmy:membership-receive-cert', payload),
  membershipSyncRevocation: (payload) => ipcRenderer.invoke('warmy:membership-sync-revocation', payload),
  profileSetPassword: (pw) => ipcRenderer.invoke('warmy:profile-set-password', pw),
  profileLogin: (pw) => ipcRenderer.invoke('warmy:profile-login', pw),
  saveVoice: (data) => ipcRenderer.invoke('warmy:save-voice', data),
  nodesList: () => ipcRenderer.invoke('warmy:nodes-list'),
  nodesPair: (nodeId, name) => ipcRenderer.invoke('warmy:nodes-pair', nodeId, name),
  nodesRevoke: (nodeId) => ipcRenderer.invoke('warmy:nodes-revoke', nodeId),
  inviteCreate: (groupId) => ipcRenderer.invoke('warmy:invite-create', groupId),
  syncPublish: (env) => ipcRenderer.invoke('warmy:sync-publish', env),
  syncPull: (nodeId) => ipcRenderer.invoke('warmy:sync-pull', nodeId),
  dshAvailable: () => ipcRenderer.invoke('warmy:dsh-available'),
  spawnDshInstance: (cfg) => ipcRenderer.invoke('warmy:spawn-dsh-instance', cfg),
  emailQueue: (mail) => ipcRenderer.invoke('warmy:email-queue', mail),
  emailList: () => ipcRenderer.invoke('warmy:email-list'),
  smtpVerify: (cfg) => ipcRenderer.invoke('warmy:smtp-verify', cfg),
  smtpList: () => ipcRenderer.invoke('warmy:smtp-list'),
  smtpAdd: (acc) => ipcRenderer.invoke('warmy:smtp-add', acc),
  smtpRemove: (id) => ipcRenderer.invoke('warmy:smtp-remove', id),
  smtpUpdate: (id, patch) => ipcRenderer.invoke('warmy:smtp-update', id, patch),
  lanStart: (port) => ipcRenderer.invoke('warmy:lan-start', port),
  lanStop: () => ipcRenderer.invoke('warmy:lan-stop'),
  lanSend: (msg) => ipcRenderer.invoke('warmy:lan-send', msg),
  lanInbox: () => ipcRenderer.invoke('warmy:lan-inbox'),
  lanStatus: () => ipcRenderer.invoke('warmy:lan-status'),
  lanDualSmoke: (opts) => ipcRenderer.invoke('warmy:lan-dual-smoke', opts),
  webgpuProbe: () => ipcRenderer.invoke('warmy:webgpu-probe'),
  meshStart: (port) => ipcRenderer.invoke('warmy:mesh-start', port),
  meshStop: () => ipcRenderer.invoke('warmy:mesh-stop'),
  peersList: () => ipcRenderer.invoke('warmy:peers-list'),
  peersAdd: (p) => ipcRenderer.invoke('warmy:peers-add', p),
  peersRemove: (id) => ipcRenderer.invoke('warmy:peers-remove', id),
  meshBroadcast: (payload, groupId) => ipcRenderer.invoke('warmy:mesh-broadcast', payload, groupId),
  meshInbox: () => ipcRenderer.invoke('warmy:mesh-inbox'),
  meshStatus: () => ipcRenderer.invoke('warmy:mesh-status'),
  // 组网状态 / 探测（R8/R9/R11）：真实现 = 本机地址、TCP 连通性、DNS、出站探测、活会话表；
  // 入站可达性本机无法验证（inboundVerified 恒 false），拿不到就如实降级，不假装检测通过。
  netStatus: () => ipcRenderer.invoke('warmy:net-status'),
  netProbe: (payload) => ipcRenderer.invoke('warmy:net-probe', payload),
  netLocalAddress: () => ipcRenderer.invoke('warmy:net-local-address'),
  netMembersPresence: (payload) => ipcRenderer.invoke('warmy:net-members-presence', payload),
  // R13：**实测**的候选端口（只读；只探测，不绑定、不改配置）——带 status，不只是端口数组
  netPortCandidates: (payload) => ipcRenderer.invoke('warmy:net-port-candidates', payload),
  meshEnable: (payload) => ipcRenderer.invoke('warmy:net-mesh-enable', payload),
  meshDisable: () => ipcRenderer.invoke('warmy:net-mesh-disable'),
  netMeshAnnounce: (reason) => ipcRenderer.invoke('warmy:net-mesh-announce', reason),
  // 本体协作层：ref / 路径门禁 + 租约（写操作前 acquire、写完 release）
  repoGuardCheckRef: (payload) => ipcRenderer.invoke('warmy:repo-guard-check-ref', payload),
  repoGuardCheckPaths: (payload) => ipcRenderer.invoke('warmy:repo-guard-check-paths', payload),
  repoGuardPreReceive: (payload) => ipcRenderer.invoke('warmy:repo-guard-pre-receive', payload),
  repoGuardInstallHooks: (payload) => ipcRenderer.invoke('warmy:repo-guard-install-hooks', payload),
  repoGuardStatus: () => ipcRenderer.invoke('warmy:repo-guard-status'),
  leaseAcquire: (payload) => ipcRenderer.invoke('warmy:lease-acquire', payload),
  leaseRelease: (payload) => ipcRenderer.invoke('warmy:lease-release', payload),
  leaseList: () => ipcRenderer.invoke('warmy:lease-list'),
  leaseCheck: (payload) => ipcRenderer.invoke('warmy:lease-check', payload),
  winMinimize: () => ipcRenderer.invoke('warmy:win-minimize'),
  winMaximize: () => ipcRenderer.invoke('warmy:win-maximize'),
  winClose: () => ipcRenderer.invoke('warmy:win-close'),
  winReload: () => ipcRenderer.invoke('warmy:win-reload'),
  groupOrchestrate: (msg) => ipcRenderer.invoke('warmy:group-orchestrate', msg),
  requestApproval: (req) => ipcRenderer.invoke('warmy:request-approval', req),
  approvalRespond: (id, allowed, scope) => ipcRenderer.invoke('warmy:approval-respond', id, allowed, scope),
  onApprovalRequest: (cb) => ipcRenderer.on('warmy:approval-request', (_e, d) => cb(d)),
  // T194 控制台：主进程**推送**真实事件（工具调用开始/结束、组网事件、错误）。
  // 只推结构化事实（cat/code/data），文案与打码都在渲染层 —— preload 不做业务判断。
  // 返回退订函数，便于重复注册时干净解绑。
  onConsoleEvent: (cb) => {
    const handler = (_e, d) => { try { cb(d); } catch { /* 渲染层自己的异常不该带崩 IPC 通道 */ } };
    ipcRenderer.on('warmy:console-event', handler);
    return () => { try { ipcRenderer.removeListener('warmy:console-event', handler); } catch { /* noop */ } };
  },
  checkpointAuto: (phase, logSeq) => ipcRenderer.invoke('warmy:checkpoint-auto', phase, logSeq),
  costSummary: () => ipcRenderer.invoke('warmy:cost-summary'),
  executorsStatus: () => ipcRenderer.invoke('warmy:executors-status'),
  executorsRunBrief: (payload) => ipcRenderer.invoke('warmy:executors-run-brief', payload),
  stateSave: (s) => ipcRenderer.invoke('warmy:state-save', s),
  stateLoad: () => ipcRenderer.invoke('warmy:state-load'),
  asrTranscribe: (p) => ipcRenderer.invoke('warmy:asr-transcribe', p),
  openChatWindow: (payload) => ipcRenderer.invoke('warmy:open-chat-window', payload),
  registerHotkey: (accel) => ipcRenderer.invoke('warmy:register-hotkey', accel),
  trayInit: () => ipcRenderer.invoke('warmy:tray-init'),
  exportSession: (payload) => ipcRenderer.invoke('warmy:export-session', payload),
  autoUpdateCheck: () => ipcRenderer.invoke('warmy:auto-update-check'),
  auditLog: (limit) => ipcRenderer.invoke('warmy:audit-log', limit),
  auditClear: () => ipcRenderer.invoke('warmy:audit-clear'),
  secureKeySave: (payload) => ipcRenderer.invoke('warmy:secure-key-save', payload),
  secureKeyLoad: (id) => ipcRenderer.invoke('warmy:secure-key-load', id),
  archiveExternal: (payload) => ipcRenderer.invoke('warmy:archive-external', payload),
  archiveList: (groupId) => ipcRenderer.invoke('warmy:archive-list', groupId),
  sessionSummary: (payload) => ipcRenderer.invoke('warmy:session-summary', payload),
  cleanupRun: (opts) => ipcRenderer.invoke('warmy:cleanup-run', opts),
  roleModelsSet: (roles) => ipcRenderer.invoke('warmy:role-models-set', roles),
  roleModelsGet: () => ipcRenderer.invoke('warmy:role-models-get'),
  groupDissolve: (groupId) => ipcRenderer.invoke('warmy:group-dissolve', groupId),
  exportAllowlist: () => ipcRenderer.invoke('warmy:export-allowlist'),
  importOpenclaw: () => ipcRenderer.invoke('warmy:import-openclaw'),
  specialModelsSet: (cfg) => ipcRenderer.invoke('warmy:special-models-set', cfg),
  specialModelsGet: () => ipcRenderer.invoke('warmy:special-models-get'),
  asrOllama: (payload) => ipcRenderer.invoke('warmy:asr-ollama', payload),
  joinRequest: (payload) => ipcRenderer.invoke('warmy:join-request', payload),
  joinPending: () => ipcRenderer.invoke('warmy:join-pending'),
  joinRespond: (payload) => ipcRenderer.invoke('warmy:join-respond', payload),
  blacklistList: () => ipcRenderer.invoke('warmy:blacklist-list'),
  blacklistRemove: (id) => ipcRenderer.invoke('warmy:blacklist-remove', id),
  groupMembers: (groupId) => ipcRenderer.invoke('warmy:group-members', groupId),
  groupInvite: (payload) => ipcRenderer.invoke('warmy:group-invite', payload),
  groupKick: (payload) => ipcRenderer.invoke('warmy:group-kick', payload),
  groupSetAdmin: (payload) => ipcRenderer.invoke('warmy:group-set-admin', payload),
  groupDirected: (payload) => ipcRenderer.invoke('warmy:group-directed', payload),
  boardSession: (groupId) => ipcRenderer.invoke('warmy:board-session', groupId),
  ccrToolOutput: (payload) => ipcRenderer.invoke('warmy:ccr-tool-output', payload),
  kbDetail: (q) => ipcRenderer.invoke('warmy:kb-detail', q),
  lastError: () => ipcRenderer.invoke('warmy:last-error'),
  clearError: () => ipcRenderer.invoke('warmy:clear-error'),
  setupState: () => ipcRenderer.invoke('warmy:setup-state'),
  setupComplete: (payload) => ipcRenderer.invoke('warmy:setup-complete', payload),
  searchMessages: (q) => ipcRenderer.invoke('warmy:search-messages', q),
  pluginInstall: (pkg) => ipcRenderer.invoke('warmy:plugin-install', pkg),
  pluginUninstall: (pkg) => ipcRenderer.invoke('warmy:plugin-uninstall', pkg),
  archivedList: () => ipcRenderer.invoke('warmy:archived-list'),
  archivedAdd: (payload) => ipcRenderer.invoke('warmy:archived-add', payload),
  archivedRestore: (id) => ipcRenderer.invoke('warmy:archived-restore', id),
  autoUpdateDownload: () => ipcRenderer.invoke('warmy:auto-update-download'),
  getChatQuery: () => { try { return new URLSearchParams(window.location.search); } catch { return new URLSearchParams(); } },
  executorRun: (task) => ipcRenderer.invoke('warmy:executor-run', task),
  executorBatch: (tasks) => ipcRenderer.invoke('warmy:executor-batch', tasks),
  assetsRetrieve: (opts) => ipcRenderer.invoke('warmy:assets-retrieve', opts),
  assetsRegister: (a) => ipcRenderer.invoke('warmy:assets-register', a),
  assetsFeedback: (id, good) => ipcRenderer.invoke('warmy:assets-feedback', id, good),
  assetsSweep: () => ipcRenderer.invoke('warmy:assets-sweep'),
  kbFromChat: (payload) => ipcRenderer.invoke('warmy:kb-from-chat', payload),
  kbDelete: (payload) => ipcRenderer.invoke('warmy:kb-delete', payload),
  saveText: (payload) => ipcRenderer.invoke('warmy:save-text', payload),
  // NOTE: warmy:diagnostics (卡顿自检) removed — feature retired.
  winAlwaysOnTop: (on) => ipcRenderer.invoke('warmy:win-always-on-top', on),
  platformInfo: () => ipcRenderer.invoke('warmy:platform'),
});
